name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install flake8 pyright
          pip install -r requirements.txt

      - name: Linting code by flake8
        run: |
          flake8 --show-source --statistics

      - name: Check types by pyright
        run: |
          pyright
